version: '3'

services:
    app:
        build: .
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        restart: always
        volumes:
            - app-sync-code-micro:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        command: ["/bin/sh","-c","mkdir -p /var/www/public; touch /var/www/public/index.php; nginx -g 'daemon off;'"]
        ports:
            - "8000:80"
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
  app-sync-code-micro:
    external: true
